title: Petr Severa
description: Osobní stránky
lang: cs

social:
  name: Petr Severa
  links:
    - https://twitter.com/segedacz
    - https://github.com/segeda
    - https://www.linkedin.com/in/petrsevera
    - https://keybase.io/segeda
